server:
  port: ${AUTH_SERVICE_PORT:8081}

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-service:8888}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${AUTH_DB:authdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:npminhtri.be@gmail.com}
    password: ${MAIL_PASSWORD:cfubhnaxnbdzsnta}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000

app:
  verification-url: ${VERIFICATION_URL:http://gateway-service:8080/auth/verify}

jwt:
  secret: ${JWT_SECRET:UCIafMmHwgsJKIgg4xVAL/eOvR3ZXD/ZnYE9AfMaMQg=}
  access-minutes: ${JWT_ACCESS_MINUTES:30}
  refresh-days: ${JWT_REFRESH_DAYS:7}
  issuer: ${JWT_ISSUER:http://auth-service:8081}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    com.auth.service: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha