# discovery-service/src/main/resources/application.yml
server:
  port: ${DISCOVERY_SERVICE_PORT:8761}

spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-service:8888}
  cloud:
    config:
      username: configuser
      password: configpass

