server:
  port: ${CONFIG_SERVICE_PORT:8888}

spring:
  application:
    name: config-service
  security:
    user:
      name: configuser
      password: configpass
  cloud:
    config:
      server:
        git:
          uri: file:/config-repo
          default-label: main
          search-paths: .
management:
  endpoints:
    web:
      exposure:
        include: health,info,env